kind: pipeline
type: docker
name: drone

platform:
  os: linux
  arch: amd64

steps:
#Should be run during CI in the Pipeline
- name: SAST
  image: hello-world:latest
  commands:
  - docker run hello-world:latest

trigger:
  branch:
  - main
