---
kind: pipeline
type: docker
name: drone

platform:
  os: linux
  arch: amd64

steps:
#Should be run during CI in the Pipeline
- name: SAST
  image: registry.fortidevsec.forticloud.com/fdevsec_sast:latest
  commands:
  - hostname
