kind: pipeline
type: docker
name: SCAN

platform:
  os: linux
  arch: amd64

steps:
#Should be run during CI in the Pipeline
- name: SAST
  commands:
  - docker run --rm --add-host fortidevsec.forticloud.com:10.34.160.80 --mount type=bind,source="$PWD",target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest

trigger:
  branch:
  - main
