kind: pipeline
type: exec
name: SCAN

platform:
  os: linux
  arch: amd64

steps:
#Should be run during CI in the Pipeline
- name: SAST
  commands:
  - docker run --rm --mount type=bind,source=$PWD,target=/scan dops-registry.fortinet-us.com/fortidevsecops/fdevsec_sast:latest

trigger:
  branch:
  - main
